<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>squad-up-api-local</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\SquadUp.ServiceDefaults\SquadUp.ServiceDefaults.csproj" />
    <ProjectReference Include="..\SquadUp.Identity.Application\SquadUp.Identity.Application.csproj" />
    <ProjectReference Include="..\SquadUp.Identity.Infrastructure\SquadUp.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\SquadUp.Profile.Application\SquadUp.Profile.Application.csproj" />
    <ProjectReference Include="..\SquadUp.Profile.Infrastructure\SquadUp.Profile.Infrastructure.csproj" />
  </ItemGroup>

</Project>
