DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'identity') THEN
        CREATE SCHEMA identity;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS identity.migration_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK_migration_history" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'identity') THEN
            CREATE SCHEMA identity;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE TABLE identity.roles (
        id uuid NOT NULL,
        name character varying(256),
        normalized_name character varying(256),
        concurrency_stamp text,
        CONSTRAINT pk_roles PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE TABLE identity.users (
        id uuid NOT NULL,
        user_name character varying(256),
        normalized_user_name character varying(256),
        email character varying(256),
        normalized_email character varying(256),
        email_confirmed boolean NOT NULL,
        password_hash text,
        security_stamp text,
        concurrency_stamp text,
        phone_number text,
        phone_number_confirmed boolean NOT NULL,
        two_factor_enabled boolean NOT NULL,
        lockout_end timestamp with time zone,
        lockout_enabled boolean NOT NULL,
        access_failed_count integer NOT NULL,
        CONSTRAINT pk_users PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE TABLE identity.role_claims (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        role_id uuid NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT pk_role_claims PRIMARY KEY (id),
        CONSTRAINT fk_role_claims_roles_role_id FOREIGN KEY (role_id) REFERENCES identity.roles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE TABLE identity.user_claims (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id uuid NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT pk_user_claims PRIMARY KEY (id),
        CONSTRAINT fk_user_claims_users_user_id FOREIGN KEY (user_id) REFERENCES identity.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE TABLE identity.user_logins (
        login_provider character varying(128) NOT NULL,
        provider_key character varying(256) NOT NULL,
        provider_display_name text,
        user_id uuid NOT NULL,
        CONSTRAINT pk_user_logins PRIMARY KEY (login_provider, provider_key),
        CONSTRAINT fk_user_logins_users_user_id FOREIGN KEY (user_id) REFERENCES identity.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE TABLE identity.user_roles (
        user_id uuid NOT NULL,
        role_id uuid NOT NULL,
        CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
        CONSTRAINT fk_user_roles_roles_role_id FOREIGN KEY (role_id) REFERENCES identity.roles (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_roles_users_user_id FOREIGN KEY (user_id) REFERENCES identity.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE TABLE identity.user_tokens (
        user_id uuid NOT NULL,
        login_provider character varying(128) NOT NULL,
        name character varying(128) NOT NULL,
        value text,
        CONSTRAINT pk_user_tokens PRIMARY KEY (user_id, login_provider, name),
        CONSTRAINT fk_user_tokens_users_user_id FOREIGN KEY (user_id) REFERENCES identity.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE INDEX ix_role_claims_role_id ON identity.role_claims (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE UNIQUE INDEX ux_roles_normalized_name ON identity.roles (normalized_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE INDEX ix_user_claims_user_id ON identity.user_claims (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE INDEX ix_user_logins_user_id ON identity.user_logins (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE INDEX ix_user_roles_role_id ON identity.user_roles (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE INDEX ix_users_normalized_email ON identity.users (normalized_email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    CREATE UNIQUE INDEX ux_users_normalized_user_name ON identity.users (normalized_user_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity.migration_history WHERE "MigrationId" = '20260903003728_InitialIdentity') THEN
    INSERT INTO identity.migration_history ("MigrationId", "ProductVersion")
    VALUES ('20260903003728_InitialIdentity', '10.0.11');
    END IF;
END $EF$;
COMMIT;
