// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SquadUp.LobbyService.Infrastructure;

#nullable disable

namespace SquadUp.LobbyService.Infrastructure.Migrations
{
    [DbContext(typeof(LobbyDbContext))]
    [Migration("20260904011444_InitialLobby")]
    partial class InitialLobby
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lobby")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SquadUp.LobbyService.Domain.Lobby", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("MembersCount")
                        .HasColumnType("integer")
                        .HasColumnName("members_count");

                    b.Property<Guid>("OwnerPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_player_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_lobbies");

                    b.ToTable("lobbies", "lobby", t =>
                        {
                            t.HasCheckConstraint("ck_lobbies_capacity_range", "capacity >= 2 AND capacity <= 100");

                            t.HasCheckConstraint("ck_lobbies_member_count_range", "members_count >= 0 AND members_count <= capacity");

                            t.HasCheckConstraint("ck_lobbies_rank_range", "minimum_ordinal > 0 AND (maximum_ordinal IS NULL OR maximum_ordinal >= minimum_ordinal)");

                            t.HasCheckConstraint("ck_lobbies_status", "status IN ('Recruiting', 'Full', 'Provisioning', 'Ready', 'Cancelled', 'Completed', 'Expired')");
                        });
                });

            modelBuilder.Entity("SquadUp.LobbyService.Domain.LobbyMember", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid")
                        .HasColumnName("lobby_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("discord_user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("display_name");

                    b.HasKey("LobbyId", "PlayerId")
                        .HasName("pk_lobby_members");

                    b.ToTable("lobby_members", "lobby", t =>
                        {
                            t.HasCheckConstraint("ck_lobby_members_discord_user_id", "char_length(discord_user_id) BETWEEN 1 AND 32");

                            t.HasCheckConstraint("ck_lobby_members_display_name", "char_length(display_name) BETWEEN 1 AND 32");

                            t.HasCheckConstraint("ck_lobby_members_rank_ordinal_positive", "rank_ordinal > 0");
                        });
                });

            modelBuilder.Entity("SquadUp.LobbyService.Infrastructure.LobbyCatalogEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_game_catalog");

                    b.ToTable("game_catalog", "lobby");

                    b.HasData(
                        new
                        {
                            Id = "dota2",
                            IsActive = true,
                            Name = "Dota 2"
                        });
                });

            modelBuilder.Entity("SquadUp.LobbyService.Infrastructure.LobbyRankTierEntry", b =>
                {
                    b.Property<string>("GameId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_id");

                    b.Property<string>("TierId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tier_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("GameId", "TierId")
                        .HasName("pk_rank_tiers");

                    b.HasIndex("GameId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_rank_tiers_game_id_ordinal");

                    b.ToTable("rank_tiers", "lobby", t =>
                        {
                            t.HasCheckConstraint("ck_rank_tiers_ordinal_positive", "ordinal > 0");
                        });

                    b.HasData(
                        new
                        {
                            GameId = "dota2",
                            TierId = "herald",
                            IsActive = true,
                            Name = "Herald",
                            Ordinal = 1
                        },
                        new
                        {
                            GameId = "dota2",
                            TierId = "guardian",
                            IsActive = true,
                            Name = "Guardian",
                            Ordinal = 2
                        },
                        new
                        {
                            GameId = "dota2",
                            TierId = "crusader",
                            IsActive = true,
                            Name = "Crusader",
                            Ordinal = 3
                        },
                        new
                        {
                            GameId = "dota2",
                            TierId = "archon",
                            IsActive = true,
                            Name = "Archon",
                            Ordinal = 4
                        },
                        new
                        {
                            GameId = "dota2",
                            TierId = "legend",
                            IsActive = true,
                            Name = "Legend",
                            Ordinal = 5
                        },
                        new
                        {
                            GameId = "dota2",
                            TierId = "ancient",
                            IsActive = true,
                            Name = "Ancient",
                            Ordinal = 6
                        },
                        new
                        {
                            GameId = "dota2",
                            TierId = "divine",
                            IsActive = true,
                            Name = "Divine",
                            Ordinal = 7
                        },
                        new
                        {
                            GameId = "dota2",
                            TierId = "immortal",
                            IsActive = true,
                            Name = "Immortal",
                            Ordinal = 8
                        });
                });

            modelBuilder.Entity("SquadUp.LobbyService.Domain.Lobby", b =>
                {
                    b.OwnsOne("SquadUp.LobbyService.Domain.RankRequirement", "RankRequirement", b1 =>
                        {
                            b1.Property<Guid>("LobbyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("GameId")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("game_id");

                            b1.Property<int?>("MaximumOrdinal")
                                .HasColumnType("integer")
                                .HasColumnName("maximum_ordinal");

                            b1.Property<int>("MinimumOrdinal")
                                .HasColumnType("integer")
                                .HasColumnName("minimum_ordinal");

                            b1.HasKey("LobbyId");

                            b1.ToTable("lobbies", "lobby");

                            b1.WithOwner()
                                .HasForeignKey("LobbyId");
                        });

                    b.Navigation("RankRequirement")
                        .IsRequired();
                });

            modelBuilder.Entity("SquadUp.LobbyService.Domain.LobbyMember", b =>
                {
                    b.HasOne("SquadUp.LobbyService.Domain.Lobby", null)
                        .WithMany("members")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SquadUp.LobbyService.Domain.PlayerRank", "Rank", b1 =>
                        {
                            b1.Property<Guid>("LobbyMemberLobbyId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("LobbyMemberPlayerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("GameId")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("rank_game_id");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("integer")
                                .HasColumnName("rank_ordinal");

                            b1.HasKey("LobbyMemberLobbyId", "LobbyMemberPlayerId");

                            b1.ToTable("lobby_members", "lobby");

                            b1.WithOwner()
                                .HasForeignKey("LobbyMemberLobbyId", "LobbyMemberPlayerId");
                        });

                    b.Navigation("Rank")
                        .IsRequired();
                });

            modelBuilder.Entity("SquadUp.LobbyService.Infrastructure.LobbyRankTierEntry", b =>
                {
                    b.HasOne("SquadUp.LobbyService.Infrastructure.LobbyCatalogEntry", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rank_tiers_game_catalog_game_id");
                });

            modelBuilder.Entity("SquadUp.LobbyService.Domain.Lobby", b =>
                {
                    b.Navigation("members");
                });
#pragma warning restore 612, 618
        }
    }
}
