// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SquadUp.Profile.Infrastructure;

#nullable disable

namespace SquadUp.Profile.Infrastructure.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20260903191038_InitialProfile")]
    partial class InitialProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("profile")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SquadUp.Profile.Domain.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.ToTable("games", "profile");
                });

            modelBuilder.Entity("SquadUp.Profile.Domain.PlayerGame", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("GameId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_id");

                    b.Property<string>("RankTierId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rank_tier_id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("region");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at_utc");

                    b.HasKey("PlayerId", "GameId")
                        .HasName("pk_player_games");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_player_games_game_id");

                    b.HasIndex("GameId", "RankTierId")
                        .HasDatabaseName("ix_player_games_game_id_rank_tier_id");

                    b.ToTable("player_games", "profile");
                });

            modelBuilder.Entity("SquadUp.Profile.Domain.PlayerProfile", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("nickname");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("PlayerId")
                        .HasName("pk_player_profiles");

                    b.ToTable("player_profiles", "profile");
                });

            modelBuilder.Entity("SquadUp.Profile.Domain.RankTier", b =>
                {
                    b.Property<string>("GameId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_id");

                    b.Property<string>("TierId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tier_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("GameId", "TierId")
                        .HasName("pk_rank_tiers");

                    b.HasIndex("GameId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_rank_tiers_game_id_ordinal");

                    b.ToTable("rank_tiers", "profile");
                });

            modelBuilder.Entity("SquadUp.Profile.Domain.PlayerGame", b =>
                {
                    b.HasOne("SquadUp.Profile.Domain.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_games_games_game_id");

                    b.HasOne("SquadUp.Profile.Domain.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_games_player_profiles_player_id");

                    b.HasOne("SquadUp.Profile.Domain.RankTier", null)
                        .WithMany()
                        .HasForeignKey("GameId", "RankTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_games_rank_tiers_game_id_rank_tier_id");
                });

            modelBuilder.Entity("SquadUp.Profile.Domain.RankTier", b =>
                {
                    b.HasOne("SquadUp.Profile.Domain.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rank_tiers_games_game_id");
                });
#pragma warning restore 612, 618
        }
    }
}
