<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SquadUp.LobbyService.Application\SquadUp.LobbyService.Application.csproj" />
    <ProjectReference Include="..\SquadUp.LobbyService.Infrastructure\SquadUp.LobbyService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
